### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/bioc2022_tidytranscriptomics#14]
Keeping track of what we still need to do

- [x] [update slides](https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/blob/master/bioc2022_tidytranscriptomics.pdf) @stemangiola 
- [x] [change Seurat commands to Bioc](https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/pull/10#issuecomment-1187002390) @stemangiola 
- [x] [add explanation for map/map2 etc](https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/pull/10#issuecomment-1188246613) @mblue9 
- [x] adjust slides e.g. remove single cell pic @stemangiola 
- [x] try fix actions for tidy packages @mblue9 (just tidybulk not passing yet)
- [x] review info in email I sent Jul 22 @stemangiola 
- [x] edits to workshop from today's meeting @mblue9 
- [x] replace tidyfeaturomics in tidySingleCellExperiment website
- [x] investigate why base R code block different to tidy
- [x] fix `restore_SingleCellExperiment_show` https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/issues/17 @stemangiola

**Comment by mblue9** [comment]
For `investigate why base R code block different to tidy` the difference is because the base R code was using the raw counts assay while tidy join_features uses the logcounts assay. 

I've changed the base R code to use logcounts [here](https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/commit/d6b5baf4581b5ac6c7a7c83b0472e6a665eba3ad) (if that's not right let me know). 

Noticed that there doesn't seem to be a way to use the raw counts with tidySCE `join_features` here, or to specify which assay to use if multiple present, so opened issue in tidySCE to note that.

**Comment by stemangiola** [comment]
> Noticed that there doesn't seem to be a way to use the raw counts with tidySCE `join_features` here, or to specify which assay to use if multiple present, so opened issue in tidySCE to note that. It's not something that has to be fixed before workshop I think.

`join_features` should have an `assay` argument `assay="counts"`

**Comment by mblue9** [comment]
Ah perfect that works 👍 I'll close the other issue.
