### ISSUE TITLE
options("restore_SingleCellExperiment_show" = FALSE)` doesn't work?

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/bioc2022_tidytranscriptomics#17]
See issue here https://github.com/stemangiola/tidySingleCellExperiment/issues/45
If it is a bug and no time to fix before workshop we could remove the `restore_SingleCellExperiment_show`

**Comment by stemangiola** [comment]
Hello @mblue9 I have fixed it and merged with the version 1.7.4
