### ISSUE TITLE
Error creating sce from seurat object

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/bioc2022_tidytranscriptomics#2]
I had a quick try to see if could create the sce from the seurat object but it didn't work, below. Is it due to the SCT assay being 6 genes & the RNA assay being more? 

```
> seurat_obj <- bioc2022tidytranscriptomics::seurat_obj

> library(Seurat)

Attaching SeuratObject
Attaching sp

> sce <- as.SingleCellExperiment(seurat_obj)
Error in method(object) : all assays must have the same nrow and ncol

> seurat_obj
An object of class Seurat 
3006 features across 36683 samples within 2 assays 
Active assay: SCT (6 features, 0 variable features)
 1 other assay present: RNA
 1 dimensional reduction calculated: umap
```

**Comment by mblue9** [comment]
Heya @stemangiola can you add the `sce_obj` used here? https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/pull/3/files#diff-db5fd574a94089482e830b898306cc74eb014b6ee6b7a57433cd80ab4989f5fbR78

**Comment by mblue9** [comment]
@stemangiola on merging the PR with the sce_obj we get this error below. Is there a SingleCellExperiment method equivalent for Seurat's FeaturePlot?
```
Quitting from lines 212-229 (tidytranscriptomics_case_study.Rmd) 
Error: processing vignette 'tidytranscriptomics_case_study.Rmd' failed with diagnostics:
'FeaturePlot' is not an exported object from 'namespace:SingleCellExperiment'
--- failed re-building ‘tidytranscriptomics_case_study.Rmd’
```

**Comment by stemangiola** [comment]
Yes there is. I will have a look tomorrow

**Comment by mblue9** [comment]
Fixed so closing
